### ISSUE TITLE
Seg Fault when loading browser

### ISSUE THREAD

**Issue by Coirt** [23volts/23volts-vcv#18]
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000067e98cdb in plugin!_ZN15MidiLearnButton4stepEv ()
   from C:\msys64\home\Phil\rack-1.1.7a\rack\plugins\23volts\plugin.dll
(gdb) bt
#0  0x0000000067e98cdb in plugin!_ZN15MidiLearnButton4stepEv ()
   from C:\msys64\home\Phil\rack-1.1.7a\rack\plugins\23volts\plugin.dll
#1  0x00000000004a867b in rack::widget::Widget::step (this=0x21d6d1e0)
    at src/widget/Widget.cpp:151
#2  0x00000000004a867b in rack::widget::Widget::step (this=0x21d6d120)
    at src/widget/Widget.cpp:151
#3  0x00000000004a867b in rack::widget::Widget::step (
    this=this@entry=0x21d6d020) at src/widget/Widget.cpp:151
#4  0x00000000004a89d0 in rack::widget::FramebufferWidget::step (
    this=0x21d6d020) at src/widget/FramebufferWidget.cpp:19
#5  0x00000000004a867b in rack::widget::Widget::step (this=0x5aa3620)
    at src/widget/Widget.cpp:151
#6  0x00000000004a867b in rack::widget::Widget::step (this=0x5aa3590)
    at src/widget/Widget.cpp:151
#7  0x00000000004a867b in rack::widget::Widget::step (
    this=this@entry=0x5aa1780) at src/widget/Widget.cpp:151
#8  0x00000000004a6d9b in rack::ui::SequentialLayout::step (this=0x5aa1780)
    at src/ui/SequentialLayout.cpp:14
#9  0x00000000004a867b in rack::widget::Widget::step (
    this=this@entry=0x5aa16b0) at src/widget/Widget.cpp:151
#10 0x00000000004a4b7d in rack::ui::MarginLayout::step (this=0x5aa16b0)
    at src/ui/MarginLayout.cpp:10
#11 0x00000000004a867b in rack::widget::Widget::step (this=0x5aa0940)
    at src/widget/Widget.cpp:151
#12 0x00000000004a867b in rack::widget::Widget::step (
    this=this@entry=0x5aa08b0) at src/widget/Widget.cpp:151
#13 0x00000000004a4565 in rack::ui::ScrollWidget::step (this=0x5aa08b0)
    at src/ui/ScrollWidget.cpp:36
#14 0x00000000004a867b in rack::widget::Widget::step (this=0x5a9bc70)
    at src/widget/Widget.cpp:151
#15 0x00000000004a867b in rack::widget::Widget::step (this=0x5a9bc00)
    at src/widget/Widget.cpp:151
#16 0x00000000004a867b in rack::widget::Widget::step (this=0x1f979340)
    at src/widget/Widget.cpp:151
#17 0x0000000000492b21 in rack::app::Scene::step (this=0x1f979340)
    at src/app/Scene.cpp:68
#18 0x000000000045a270 in rack::Window::run (this=0x5a33d40)
    at src/window.cpp:393
#19 0x0000000000783c05 in main (argc=<optimized out>, argv=<optimized out>)
    at src/main.cpp:203
(gdb)

```

**Comment by RemiCollin** [comment]
Are you using the version from the library or a compiled version ? VCV library released the 1.1.1 which was not the last version, should be 1.1.2..

**Comment by Petervos2018** [comment]
Here to report the same , and yes it's version 1.1.1 in the browsers that kills it, back to 1.0.1.
I see you already posted this : https://github.com/VCVRack/library/issues/617#issuecomment-573727827

**Comment by RemiCollin** [comment]
For some reason, the library seemed to have not released the last version of the 23volts package, which should be 1.1.2. The version 1.1.1 makes the browser crash on Win10. Artem Leonov has published the good version of the plugin on his patreon, for those experiencing the crash just replace with the ZIP file and you should be fine : https://www.patreon.com/posts/33090668

**Comment by Coirt** [comment]
Just one of those things I suppose. Automation glitch probably, damn robots.

**Comment by RemiCollin** [comment]
Yes probably. I'm in the process of having Azure Pipeline setup for the repo, so hopefully it will help things with Beta testing on all platforms (I can test on OSX/Linux but don't own a windows box)

**Comment by Coirt** [comment]
I'll watch the repo for new versions and build on windows. If you need a distribution just let me know!

**Comment by RemiCollin** [comment]
@Coirt  Thanks I'll let you know. Hopefully I'll have azure pipeline working by then, it builds ok but it fails when publishing the release (apparently a known issue on azure side which should be fixed soon)
